const MAX_DIST = 100;
const WIDTH = 80;
const HEIGHT = 100;
const PIXELS_PER_METER = 10;
const FLOOR_V_OFFSET = 50;
const WAVE_ANGULAR_RES = 20;

// PARAMETERS TO CHANGE:
const RELAY_RATIO = 0.3;
const STATIC_NODE_COUNT = 60;
const MOBILE_NODE_COUNT = 20;
const TTL = 10;
